theme: minima
title: Dave Sugden
description: DevOps & Football. LUFC & Scarborough. Write tech, run @leedsmusicscene and @leedsgigguide.
author:
  name: Dave Sugden
  email: "davelms@gmail.com"
minima:
  social_links:
    twitter: davelms
    github: davelms
    linkedin: davelms
twitter_username: davelms
github_username: davelms
linkedin_username: davelms
rss: rss
