theme: minima
title: Dave Sugden
description: DevOps & Football. LUFC & Scarborough. <a href="https://davelms.medium.com">Write tech</a>, run <a href="https://twitter.com/leedsmusicscene">@leedsmusicscene</a> and <a href="https://twitter.com/leedsgigguide">@leedsgigguide]</a>
minima:
  social_links:
    twitter: davelms
    github: davelms
    linkedin: davelms
