plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
title: Dave Sugden
description: DevOps & Football. LUFC & Scarborough. Write tech, run @leedsmusicscene and @leedsgigguide.
author:
  name: Dave Sugden
  email: "davelms@gmail.com"
minima:
  social_links:
    twitter: davelms
    github: davelms
    linkedin: davelms
