theme: minima
title: Dave Sugden
description: DevOps & Football. LUFC & Scarborough. Write tech to https://davelms.medium.com Run [@leedsmusicscene](https://twitter.com/leedsmusicscene) and [@leedsgigguide](https://twitter.com/leedsgigguide)
minima:
  social_links:
    twitter: davelms
    github: davelms
    linkedin: davelms
